BookStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls', namespace='books')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payments.urls', namespace='payments')),
    path('api/', include('api.urls', namespace='api')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from .views import BooksListView, BooksDetailView


app_name = 'api'


urlpatterns = [
    path('books/', BooksListView.as_view()),
    path('books/<int:pk>/', BooksDetailView.as_view()),
]

cart/urls.py
from django.urls import path
from .views import cart_add, cart_remove, cart_clear, cart_detail


app_name = 'cart'


urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add,name='add'),
    path('remove/<int:product_id>', cart_remove, name='remove'),
    path('remove/all/', cart_clear, name='clear'),
]

orders/urls.py
from django.urls import path
from .views import create_order


app_name = 'orders'


urlpatterns = [
    path('create/', create_order, name='create'),
]

cart/forms.py
from django import forms

QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class AddBookForm(forms.Form):
    quantity = forms.TypedChoiceField( label='Количество', choices=QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from books.models import Book
from .forms import AddBookForm
from .cart import Cart

# Create your views here.


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Book, id=product_id)
    form = AddBookForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd['quantity'],
            override_quantity=cd['override'],
        )
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Book, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


@require_POST
def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = AddBookForm(initial={
            'quantity': item['quantity'],
            'override': True,
        })
    context = {'cart': cart}
    return render(request, 'cart/cart_detail.html', context)

templates/cart/cart_detail.html
{% extends "base.html" %}
{% block title %}Корзина{% endblock title %}
{% block content %}
    Корзина товаров:
    <table class="cart">
    <thead>
      <tr>
        <th></th>
        <th>Товар</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Цена за единицу</th>
        <th>Цена</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url "cart:add" product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="Обновить">
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url "cart:remove" product.id %}" method="post">
                <input type="submit" value="Удалить">
                {% csrf_token %}
              </form>
            </td>
            <td>₽{{ item.price }}</td>
            <td>₽{{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr>
        <td>
          <form action="{% url "cart:clear" %}">
            <input type="submit" value="Очистить">
          </form>
        </td>
        <td>
          <form action="{% url "orders:create" %}">
            {% csrf_token %}
            <input type="submit" value="Купить"{% if not cart|length %}disabled{% endif %}>
          </form>
        </td>
        <td colspan="4">Общая стоимость</td>
        <td class="num">₽{{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>
{% endblock content %}