BookStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls', namespace='books')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payments.urls', namespace='payments')),
    path('api/', include('api.urls', namespace='api')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from .views import BooksListView, BooksDetailView


app_name = 'api'


urlpatterns = [
    path('books/', BooksListView.as_view()),
    path('books/<int:pk>/', BooksDetailView.as_view()),
]

books/urls.py
from django.urls import path
from .views import books_list, books_detail, add_comment, search_books


app_name = 'books'


urlpatterns = [
    path('', books_list, name='books_list'),
    path('author/<slug:author>/', books_list, name='author_books'),
    path('genre/<slug:genre>/', books_list, name='genre_books'),
    path('books/<int:pk>/', books_detail, name='books_detail'),
    path('books/search/', search_books, name='search_books'),
    path('comment/add/<int:pk>', add_comment, name='add_comment')
]

cart/urls.py
from django.urls import path
from .views import cart_add, cart_remove, cart_clear, cart_detail


app_name = 'cart'


urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add,name='add'),
    path('remove/<int:product_id>', cart_remove, name='remove'),
    path('remove/all/', cart_clear, name='clear'),
]

books/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.


class Author(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50)
    
    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=('name',))
        ]
    
    def __str__(self) -> str:
        return f'Автор: {self.name}'


class Genre(models.Model):
    genre_name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50)
    
    class Meta:
        ordering = ['genre_name']
        indexes = [
            models.Index(fields=('genre_name',))
        ]
    
    def __str__(self) -> str:
        return f'Жанр: {self.genre_name}'
    
    
class Book(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='image/books/%Y/%m/%d', blank=True, null=True)
    book_pdf = models.FileField(upload_to='files/books/%Y/%m/%d', blank=True, null=True)
    description = models.TextField()
    number_of_pages = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    release_date = models.DateField()
    auhtor = models.ManyToManyField(Author, related_name='books')
    genre = models.ManyToManyField(Genre, related_name='books')
    created = models.DateTimeField(auto_now_add=True, unique=True)
    
    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=('id', 'slug')),
            models.Index(fields=('name',)),
            models.Index(fields=('-created',))
        ]
        
    def get_absolute_url(self):
        return reverse('books:books_detail', args=[self.id])
    
    def __str__(self) -> str:
        return f'Книга: {self.name}'
    

class Commentary(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=50)
    comment = models.TextField(max_length=250)
    status = models.BooleanField(default=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='comments')
    created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=('-created',)),
            models.Index(fields=('status',))
        ]   

books/forms.py
from django import forms
from .models import Commentary


class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Commentary
        fields = ['email', 'name', 'comment']
    

books/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST, require_GET
from django.views.decorators.cache import cache_page
from django.core.exceptions import ObjectDoesNotExist
from django.http.response import Http404
from cart.forms import AddBookForm
from .models import Book, Commentary
from .forms import AddCommentForm

# Create your views here.


@require_GET
def books_detail(request, pk):
    try:
        book = Book.objects.filter(id=pk).prefetch_related ('auhtor', 'genre').first()
    except ObjectDoesNotExist:
        return Http404()
    comments_q = Commentary.objects.filter(book=book)
    context = {'book': book, 'comments': comments_q, 'book_form': AddBookForm(), 'comment_form': AddCommentForm()}
    return render(request, 'books/books_detail.html', context)


@require_GET
@cache_page(60 * 15)
def books_list(request, author=None, genre=None):
    books = Book.objects.all()
    
    if author:
        books = books.filter(auhtor__slug=author)
    if genre:
        books = books.filter(genre__slug=genre)
    
    context = {'books': books}
    return render(request, 'books/books_list.html', context)


@require_POST
def add_comment(request, pk):
    form = AddCommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        book = get_object_or_404(Book, id=pk)
        comment.book = book
        comment.save()

    return redirect('books:books_detail', pk)


@require_GET
def search_books(request):
    query = request.GET.get('search')
    search_res = Book.objects.filter(name__icontains=query)
    context = {'books': search_res}
    return render(request, 'books/books_list.html', context)
        

templates/books/books_detail.html
{% extends "base.html" %}
{% block title %}{{ book.name }}{% endblock title %}
{% block content %}
    <div class="book-info">
        <img src="{{ book.image.url }}" alt="Error">
        <form action="{% url "cart:add" book.id %}" method="post">
            {{ book_form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Добавить в корзину">
        </form>
        <p><span>{{ book.name }}</span></p>
        <p><span>Автор</span>: {% for author in book.auhtor.all %}<a href="{% url "books:author_books" author.slug %}">{{ author.name }}</a> {% endfor %}</p>
        <p><span>Жанр</span>: {% for genre in book.genre.all %}<a href="{% url "books:genre_books" genre.slug %}">{{ genre.genre_name }}</a> {% endfor %}</p>
        <p><span>Цена</span>: {{ book.price }}₽</p>
        <p><span>Описание</span>: {{ book.description }}</p>
        <form action="{% url "books:add_comment" book.id %}" method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Отправить">
        </form>
        {% for comment in comments %}
        <table class="comment">
            <tr>
              <td>{{ comment.created }}</td>
              <td>{{ comment.name }}</th>
              <td>{{ comment.email }}</th>
              <td>{{ comment.comment }}</th>
            </tr>
        {% endfor %}
        
    </div>
{% endblock content %}

templates/books/books_list.html
{% extends "base.html" %}
{% block title %}Главная{% endblock title %}
{% block content %}
    {% if books %}
    <div class="books">
    {% for book in books %}
        <div class="book">
            <a class="img" href="{{ book.get_absolute_url }}"><img src="{{ book.image.url }}" alt="" width="200" height="300"></a>
            <div class="text">
                <a href="{{ book.get_absolute_url }}">{{ book.name }}</a>
                <p>{{ book.description }}</p>
            </div>
        </div>
    {% endfor %}
    {% else %}
    <p>Ничего не найдено</p>
    {% endif %}
</div>
{% endblock content %}