BookStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls', namespace='books')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payments.urls', namespace='payments')),
    path('api/', include('api.urls', namespace='api')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from .views import BooksListView, BooksDetailView


app_name = 'api'


urlpatterns = [
    path('books/', BooksListView.as_view()),
    path('books/<int:pk>/', BooksDetailView.as_view()),
]

books/urls.py
from django.urls import path
from .views import books_list, books_detail, add_comment, search_books


app_name = 'books'


urlpatterns = [
    path('', books_list, name='books_list'),
    path('author/<slug:author>/', books_list, name='author_books'),
    path('genre/<slug:genre>/', books_list, name='genre_books'),
    path('books/<int:pk>/', books_detail, name='books_detail'),
    path('books/search/', search_books, name='search_books'),
    path('comment/add/<int:pk>', add_comment, name='add_comment')
]

cart/urls.py
from django.urls import path
from .views import cart_add, cart_remove, cart_clear, cart_detail


app_name = 'cart'


urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add,name='add'),
    path('remove/<int:product_id>', cart_remove, name='remove'),
    path('remove/all/', cart_clear, name='clear'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Base{% endblock title %}</title>
    <link rel="stylesheet" href="{% static "/css/styles.css" %}">
</head>
<body>
    {% block menu %}
    <ul class="menu">
        <li><a href="{% url "books:books_list" %}">Главная</a></li>
        <li><a href="{% url "cart:cart_detail" %}">Корзина</a></li>
        <li>
            <form id="form" action="{% url "books:search_books" %}" method="get"></form>
                <input type="text" placeholder="поиск" form="form" name="search">
                <input type="submit" value="Искать" form="form">
        </li>
    </ul>
    {% endblock menu %}
    {% block content %}{% endblock content %}
</body>
</html>